In [2]:
import pandas as pd

In [6]:
df = pd.read_csv("school_salary.csv")

In [8]:
df.columns

Index(['student_id', 'cgpa', 'branch', 'college_tier', 'python_skill',
       'dsa_skill', 'ml_skill', 'web_dev_skill', 'coding_score',
       'communication_score', 'aptitude_score', 'internships', 'projects',
       'backlogs', 'resume_score', 'skill_score', 'placed', 'company_type',
       'job_role', 'salary_lpa'],
      dtype='object')

In [17]:
df.set_index("student_id").head(3)
#df.reset_index()

,cgpa,branch,college_tier,python_skill,dsa_skill,ml_skill,web_dev_skill,coding_score,communication_score,aptitude_score,internships,projects,backlogs,resume_score,skill_score,placed,company_type,job_role,salary_lpa
student_id,,,,,,,,,,,,,,,,,,,
S0,6.87,Civil,1,1,1,0,0,15.6,4.3,92.0,1,3,0,62.6,2,1,MNC,Software Engineer,63.55
S1,6.52,Civil,2,1,0,0,1,13.9,5.8,62.0,1,6,0,77.5,2,1,MNC,Data Scientist,75.17
S2,5.33,IT,1,1,1,1,0,9.8,8.1,66.4,0,5,1,76.0,3,1,MNC,Software Engineer,80.44

In [19]:
df["branch"].value_counts()

branch
IT            1564
Civil         1504
ECE           1499
CSE           1496
EEE           1478
Mechanical    1459
Name: count, dtype: int64

In [20]:
df.nunique()

student_id             9000
cgpa                    501
branch                    6
college_tier              3
python_skill              2
dsa_skill                 2
ml_skill                  2
web_dev_skill             2
coding_score           1001
communication_score      61
aptitude_score          601
internships               4
projects                  6
backlogs                  4
resume_score            893
skill_score               5
placed                    2
company_type              4
job_role                  4
salary_lpa             4343
dtype: int64

In [25]:
df.job_role.value_counts()

job_role
Web Developer        1939
Data Scientist       1938
Software Engineer    1937
Analyst              1888
Name: count, dtype: int64

In [29]:
# 1298 kisinin isi yok
unemployee_df = df[df["job_role"].isnull()]

In [32]:
df[df["job_role"]== "Data Scientist"].coding_score.describe()

count    1938.000000
mean       51.718782
std        28.480030
min         0.000000
25%        27.800000
50%        52.200000
75%        76.300000
max       100.000000
Name: coding_score, dtype: float64

In [33]:
#data scientist isleri icin coding scoru dusuk olup nasil ise giris yaptiklarina baktim
df[df["job_role"]== "Data Scientist"].sort_values("coding_score")

,student_id,cgpa,branch,college_tier,python_skill,dsa_skill,ml_skill,web_dev_skill,coding_score,communication_score,aptitude_score,internships,projects,backlogs,resume_score,skill_score,placed,company_type,job_role,salary_lpa
7501,S7501,9.59,ECE,1,1,1,1,0,0.0,6.7,53.2,2,6,0,102.3,3,1,MNC,Data Scientist,74.69
7437,S7437,9.01,CSE,3,1,1,1,1,0.1,7.6,44.0,0,5,1,89.1,4,1,Mid-size,Data Scientist,52.19
4534,S4534,7.56,EEE,3,1,1,0,1,0.1,4.0,77.5,0,5,0,68.4,3,1,MNC,Data Scientist,64.23
8680,S8680,6.14,IT,2,0,1,0,0,0.1,9.0,40.0,2,1,0,60.7,1,1,Startup,Data Scientist,40.81
1620,S1620,8.34,Mechanical,1,1,1,0,1,0.1,7.2,52.9,0,1,0,60.3,3,1,MNC,Data Scientist,79.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7439,S7439,7.88,Mechanical,3,1,1,0,1,99.8,4.3,76.7,1,2,0,59.9,3,1,Mid-size,Data Scientist,59.36
2051,S2051,5.80,Mechanical,2,1,0,0,0,99.9,8.6,54.5,1,4,1,61.9,1,1,Startup,Data Scientist,44.20
4981,S4981,6.89,Civil,1,1,0,1,1,100.0,5.5,92.1,1,1,0,63.6,3,1,MNC,Data Scientist,79.77
6907,S6907,8.75,ECE,1,1,1,0,1,100.0,4.0,43.1,1,4,0,69.1,3,1,Top Tech,Data Scientist,98.88
1761,S1761,8.61,Civil,1,1,1,0,0,100.0,4.2,63.7,0,2,0,43.2,2,1,MNC,Data Scientist,72.62

In [39]:
#hem issiz olmayan hemde coding score u 10 nun altinda olan veriyi gormek istedim
df[(df["coding_score"]<10.0) & (~df["job_role"].isnull())].sort_values("coding_score")

,student_id,cgpa,branch,college_tier,python_skill,dsa_skill,ml_skill,web_dev_skill,coding_score,communication_score,aptitude_score,internships,projects,backlogs,resume_score,skill_score,placed,company_type,job_role,salary_lpa
4163,S4163,5.44,CSE,1,0,1,0,1,0.0,9.3,44.0,3,1,0,87.2,2,1,MNC,Web Developer,80.43
7501,S7501,9.59,ECE,1,1,1,1,0,0.0,6.7,53.2,2,6,0,102.3,3,1,MNC,Data Scientist,74.69
4846,S4846,7.30,EEE,1,1,1,0,1,0.0,7.3,97.8,2,6,2,102.6,3,1,MNC,Software Engineer,91.92
6486,S6486,7.82,CSE,1,1,0,0,1,0.0,4.5,72.5,2,2,0,67.9,2,1,MNC,Software Engineer,77.46
7437,S7437,9.01,CSE,3,1,1,1,1,0.1,7.6,44.0,0,5,1,89.1,4,1,Mid-size,Data Scientist,52.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1522,S1522,8.95,ECE,2,0,1,0,1,9.9,7.3,71.8,0,1,0,45.7,2,1,MNC,Analyst,76.91
1133,S1133,9.69,ECE,3,0,1,0,1,9.9,7.9,87.5,1,2,0,65.0,2,1,MNC,Data Scientist,67.63
1007,S1007,5.68,ECE,1,1,1,1,1,9.9,10.0,64.0,0,5,0,95.3,4,1,MNC,Data Scientist,80.38
763,S763,7.44,CSE,1,1,1,0,1,9.9,8.9,80.5,0,3,2,70.5,3,1,MNC,Analyst,80.71
8437,S8437,9.66,IT,1,1,1,1,0,9.9,5.5,48.2,1,6,0,83.7,3,1,MNC,Data Scientist,88.38